# Generated by Django 3.1.4 on 2021-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeoNoteApp', '0003_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
