# Generated by Django 3.1.4 on 2021-06-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeoNoteApp', '0005_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='geolocation',
        ),
    ]
