# Generated by Django 3.1.4 on 2021-07-01 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeoNoteApp', '0006_remove_rental_geolocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.AddField(
            model_name='places',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NeoNoteApp.group'),
        ),
    ]
