# Generated by Django 3.1.4 on 2021-07-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeoNoteApp', '0008_auto_20210701_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='places',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
