# Generated by Django 3.1.4 on 2021-07-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeoNoteApp', '0009_auto_20210701_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='city',
        ),
        migrations.RemoveField(
            model_name='places',
            name='country',
        ),
        migrations.RemoveField(
            model_name='places',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='places',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
