# Generated by Django 3.1.4 on 2021-07-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeoNoteApp', '0011_auto_20210701_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='folder',
            field=models.FileField(blank=True, upload_to='place_images'),
        ),
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.ImageField(blank=True, upload_to='place_images'),
        ),
    ]
